### ISSUE TITLE
Sample Archive Anpassungen

### ISSUE THREAD

**Issue by KuhlmannDatenbank** [DavidBlaa/SampleArchive#29]
- [ ]  1. Wie wird der Name von Owner eingegeben? Vorname zuerst oder zuletzt?
- [ ]  2. i-info ist nicht aktiv
- [x] 3. Sample type: Sieved & Ground bitte zwei Felder draus machen mit der Auwahl Yes/No.
- [x] 4. "Depth range", "Soil" und "Archive" kann ich nicht aktivieren.  
- [x] 5. Depth Range -> tooltip cm
- [x] 6. mineral soil -> depth interval -> Integer mit tooltip cm

**Comment by KuhlmannDatenbank** [comment]
Punkt 4. erledigt

**Comment by DavidBlaa** [comment]
+ Depth Range -> tooltip cm
+ mineral soil -> depth interval -> Integer mit tooltip cm

**Comment by DavidBlaa** [comment]
1. Vorname zuerst

**Comment by DavidBlaa** [comment]
2. i-info ist nicht aktiv:
-----------------------
Das ist kein Button zu klicken. Wenn du mit der Mouse kurz drüber gehst, müsstest ein tooltip erscheinen.

**Comment by DavidBlaa** [comment]
Aufgaben sind erledigt und online

**Comment by KuhlmannDatenbank** [comment]
> 
> 
>     * Depth Range -> tooltip cm
> 
>     * mineral soil -> depth interval -> Integer mit tooltip cm

* Depth Range ->Tooltip ist in qubic metern. Das funktioniert beim Pit/Loch Länge, Breite,Höhe. Beim Bohrkern wird gerne einfach nur die Gesamttiefe angegeben. Was tun? 
* Punkt3?

**Comment by KuhlmannDatenbank** [comment]
Dried at temperature |   |   |  
* Was hattest Du eigentlich mit dem >>status<< der Probe vor.  Bin mir nicht sicher ob mit dem Alter des Waldes der Eintrag so gedacht war. Was könntes es außerdem bedeuten?

**Comment by KuhlmannDatenbank** [comment]
Northern statt Nothern laditude
